const FORMAS_PAGO_PRESENCIAL = {
  tipo: 'presencial',
  textoSeña: 'Podés reservar tu lugar con una seña de $50.000. El saldo se abona antes del inicio del curso.',
  metodos: [
    'Efectivo — 10% de descuento',
    'Transferencia — plan de pago disponible',
    'Tarjeta de crédito o débito — 10% de recargo',
  ],
}

const FORMAS_PAGO_ONLINE = {
  tipo: 'online',
  textoSeña: 'El pago es en su totalidad al momento de inscribirse.',
  metodos: [
    'Transferencia',
    'Tarjeta de crédito o débito — 10% de recargo',
    'PayPal',
  ],
}

export const CURSOS = [
  {
    id: 'lash-artist',
    nombre: 'De Cero a Lash Artist',
    descripcion: 'Una mentoría integral diseñada para quienes quieren construir una carrera profesional en extensiones de pestañas desde cero. En tres meses, sin experiencia previa, vas a desarrollar la técnica, el criterio y la confianza de una verdadera Lash Artist.',
    duracion: '3 meses · Clases virtuales + Prácticas presenciales',
    modalidad: 'Híbrido',
    sede: 'Villa Ballester',
    material: 'Incluido',
    certificacion: 'Certificado por módulo y final',
    precio: 399999,
    precioTachado: 444999,
    fechas: '27 de julio',
    cupos: 6,
    nivel: 'Principiantes',
    nivelRequerido: 'principiante',
    labelNivel: 'Apto para principiantes',
    filtros: ['ini', 'hyb'],
    imagen: '/images/curso-lash-artist.webp',
    soldOut: true,
    grupos: [
      {
        id: 'grupo-1',
        nombre: 'Grupo 1',
        cupos: 0,
        presenciales: [
          'Sábado 8 de agosto · 9hs',
          'Sábado 29 de agosto · 9hs',
          'Sábado 12 de septiembre · 9hs',
          'Sábado 26 de septiembre · 9hs',
        ],
      },
      {
        id: 'grupo-2',
        nombre: 'Grupo 2',
        cupos: 2,
        presenciales: [
          'Sábado 15 de agosto · 9hs',
          'Sábado 5 de septiembre · 9hs',
          'Sábado 19 de septiembre · 9hs',
          'Sábado 3 de octubre · 9hs',
        ],
      },
    ],
    virtuales: [
      'Lunes 27 de julio · 18hs',
      'Miércoles 29 de julio · 18hs',
      'Lunes 3 de agosto · 18hs',
      'Miércoles 5 de agosto · 18hs',
      'Miércoles 19 de agosto · 18hs',
      'Lunes 25 de agosto · 18hs',
      'Lunes 7 de septiembre · 18hs',
      'Lunes 21 de septiembre · 18hs',
    ],
    temario: [
      'Fundamentos de las extensiones de pestañas',
      'Bioseguridad y preparación del área de trabajo',
      'Análisis del ojo y diseños personalizados',
      'Técnica clásica · Efecto máscara · Fibras tecnológicas · Diseños avanzados · Diseños en tendencia · Diseños creativos',
      'Dirección, aislamiento y adhesión',
      'Retención y adhesivos',
      'Salud ocular, errores comunes y correcciones',
      'Generar una marca, administrar tu propio negocio',
      'Cómo vender y atraer clientas reales',
      'Prácticas en modelo real',
    ],
    kit: { disponible: true, precio: 115000 },
    formasPago: FORMAS_PAGO_PRESENCIAL,
  },
  {
    id: 'korean-lift',
    nombre: 'Korean Lift — Técnica Coreana',
    descripcion: 'Una capacitación diseñada para aprender desde cero la técnica de Lifting Coreano, logrando pestañas más curvas, definidas y con un resultado natural y duradero. Vas a conocer el paso a paso, los productos y las claves para realizar el servicio de manera profesional.',
    duracion: '1 día · Teoría + Práctica',
    modalidad: 'Presencial',
    sede: 'Villa Ballester',
    material: 'Incluido',
    certificacion: 'Certificado de asistencia',
    precio: 129999,
    precioTachado: 144999,
    fechas: '6 de septiembre',
    cupos: 0,
    nivel: 'Avanzadas',
    nivelRequerido: 'con-experiencia',
    labelNivel: 'Requiere conocimientos previos',
    filtros: ['adv'],
    imagen: '/images/curso-korean-lift.webp',
    soldOut: false,
    temario: [
      'Introducción al Lifting Coreano',
      'Lifting Tradicional vs Coreano',
      'Química',
      'Anatomía de las Pestañas',
      'Higiene y Seguridad',
      'Porosidad',
      'Herramientas y Productos',
      'Tips y Claves para un Resultado Óptimo',
      'Armado de un Kit de Lifting Coreano',
      'Cuidados y Tips Post Servicios',
      'Costos',
    ],
    kit: { disponible: false, precio: null },
    formasPago: FORMAS_PAGO_PRESENCIAL,
  },
  {
    id: 'lash-duo',
    nombre: 'Lash Dúo',
    descripcion: 'Una capacitación diseñada para aprender desde cero dos técnicas fundamentales de extensiones de pestañas: Clásicas y Tech. Vas a incorporar las bases necesarias para realizar ambos servicios de manera profesional, entendiendo materiales, técnica y diseño.',
    duracion: '3 semanas · Clases virtuales + Prácticas presenciales',
    modalidad: 'Híbrido',
    sede: 'Villa Ballester',
    material: 'Incluido en prácticas',
    certificacion: 'Certificado por módulo y final',
    precio: 299000,
    precioTachado: 328900,
    fechas: '19 de octubre',
    cupos: 6,
    nivel: 'Principiantes',
    nivelRequerido: 'principiante',
    labelNivel: 'Apto para principiantes',
    filtros: ['ini', 'hyb'],
    imagen: '/images/curso-lash-duo.webp',
    soldOut: false,
    incluye: 'Materiales de la mejor calidad en las prácticas presenciales, coffee break en cada encuentro, acceso a las clases grabadas durante 3 meses, acompañamiento antes, durante y después de la cursada, grupo privado de seguimiento, y almuerzo con brindis de graduación.',
    grupos: [
      {
        id: 'grupo-1',
        nombre: 'Grupo 1',
        cupos: 6,
        presenciales: [
          'Sábado 24 de octubre · 9hs',
          'Sábado 7 de noviembre · 9hs',
        ],
        labelFormulario: 'jueves y viernes desde el 24/10',
      },
    ],
    virtuales: [
      'Lunes 19 de octubre · 18hs',
      'Miércoles 21 de octubre · 18hs',
      'Lunes 2 de noviembre · 18hs',
    ],
    grabadas: true,
    temario: [
      'Anatomía ocular y pestaña natural',
      'Contraindicaciones y enfermedades oculares',
      'Higiene y bioseguridad',
      'Herramientas y materiales',
      'Calidad de insumos y marcas',
      'Química y correcto uso del adhesivo',
      'Técnica clásica 1:1',
      'Fibras tecnológicas',
      'Diferentes tipos de volúmenes',
      'Curvas, grosores y longitudes',
      'Diseños y mappings',
      'Selección de técnica según la mirada',
      'Correcta aplicación y dirección',
      'Errores frecuentes',
      'Cuidados y mantenimiento',
      'Tips profesionales para mejorar retención y resultados',
    ],
    kit: { disponible: true, precio: 89000 },
    formasPago: FORMAS_PAGO_PRESENCIAL,
  },
  {
    id: 'lash-trends',
    nombre: 'Lash Trends — Efectos en Tendencia',
    descripcion: 'Una capacitación pensada para actualizar tu técnica e incorporar los efectos que son tendencia. Vas a aprender nuevos diseños, mappings y combinaciones para crear sets modernos, versátiles y adaptados a cada mirada.',
    duracion: '1 clase virtual',
    modalidad: 'Online',
    sede: null,
    material: null,
    certificacion: 'Certificado digital',
    precio: 49999,
    precioTachado: 54999,
    fechas: 'Miércoles 2 de septiembre · 18hs',
    cupos: null,
    nivel: 'Avanzadas',
    nivelRequerido: 'con-experiencia',
    labelNivel: 'Requiere conocimientos previos',
    filtros: ['adv', 'onl'],
    imagen: '/images/curso-lash-trends.webp',
    soldOut: false,
    incluye: 'Certificado digital y acceso a la grabación durante 7 días.',
    grupos: null,
    grabadas: true,
    temario: [
      'Actualización de técnicas y tendencias',
      'Diseño de mirada y elección del efecto',
      'Mappings básicos y avanzados',
      'Curvas básicas y avanzadas',
      'Combinación de curvas, longitudes y grosores',
      'Wispy',
      'Foxy',
      'Efecto Delineado',
      'Kim K',
      'Efecto Rímel Tech',
      'Efecto Lami',
      'Spire Lashes',
      'Técnicas para crear textura y dimensión',
      'Adaptación de los efectos a diferentes tipos de ojos',
      'Errores frecuentes y cómo corregirlos',
      'Tips para lograr sets más prolijos, definidos y comerciales',
    ],
    kit: { disponible: false, precio: null },
    formasPago: FORMAS_PAGO_ONLINE,
  },
  {
    id: 'korean-lift-online',
    nombre: 'Korean Lift — 100% Online',
    descripcion: 'Una capacitación diseñada para aprender desde cero la técnica de Lifting Coreano, logrando pestañas más curvas, definidas y con un resultado natural y duradero. Vas a conocer el paso a paso, los productos y las claves para realizar el servicio de manera profesional.',
    duracion: '1 clase virtual',
    modalidad: 'Online',
    sede: null,
    material: null,
    certificacion: 'Certificado digital',
    precio: 59999,
    precioTachado: 65999,
    fechas: 'Viernes 4 de septiembre · 18hs',
    cupos: null,
    nivel: 'Todos los niveles',
    nivelRequerido: 'principiante',
    labelNivel: 'Apto para todos los niveles',
    filtros: ['ini', 'adv', 'onl'],
    imagen: '/images/curso-korean-lift-online.webp',
    soldOut: false,
    incluye: 'Certificado digital y acceso a la grabación durante 7 días.',
    grupos: null,
    grabadas: true,
    temario: [
      'Introducción al Lifting Coreano',
      'Lifting Tradicional vs Coreano',
      'Química',
      'Anatomía de las Pestañas',
      'Higiene y Seguridad',
      'Porosidad',
      'Herramientas y Productos',
      'Tips y Claves para un Resultado Óptimo',
      'Armado de un Kit de Lifting Coreano',
      'Cuidados y Tips Post Servicios',
      'Costos',
    ],
    kit: { disponible: false, precio: null },
    formasPago: FORMAS_PAGO_ONLINE,
  },
]
