export const CURSOS = [
  {
    id: 'lash-artist',
    nombre: 'De Cero a Lash Artist',
    descripcion: 'Una mentoría integral diseñada para quienes quieren construir una carrera profesional en extensiones de pestañas desde cero. En tres meses, sin experiencia previa, vas a desarrollar la técnica, el criterio y la confianza de una verdadera Lash Artist.',
    duracion: '3 meses · 8 clases virtuales + 4 prácticas presenciales',
    modalidad: 'Híbrido',
    sede: 'Villa Ballester',
    material: 'Incluido en prácticas',
    certificacion: 'Certificado por módulo y final',
    precio: 399999,
    precioTachado: 444999,
    fechas: '27 de julio',
    cupos: 6,
    nivel: 'Principiantes',
    nivelRequerido: 'principiante',
    labelNivel: 'Apto para principiantes',
    filtros: ['ini', 'onl'],
    imagen: '/images/curso-lash-artist.webp',
  },
  {
    id: 'korean-lift',
    nombre: 'Korean Lift — Técnica Coreana',
    descripcion: 'La técnica que está redefiniendo el mercado. Incorporá a tu estudio un método que combina precisión, seguridad y resultados de alta demanda, y posicioná tu servicio en el segmento premium de 2026.',
    duracion: '1 día · Teoría + práctica',
    modalidad: 'Presencial',
    sede: 'Villa Ballester',
    material: 'Incluido',
    certificacion: 'Certificado de asistencia',
    precio: 129999,
    precioTachado: 144999,
    fechas: '25 de julio · 1 de agosto',
    cupos: 6,
    nivel: 'Avanzadas',
    nivelRequerido: 'con-experiencia',
    labelNivel: 'Requiere conocimientos previos',
    filtros: ['adv'],
    imagen: '/images/curso-korean-lift.webp',
  },
]
